name: Deploy to Production

on:
  push:
    branches:
      - prod # Пайплайн запустится при пуше/мердже в ветку prod

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Checkout code
        uses: actions/checkout@v4

      - name: 📦 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: 🛠️ Install dependencies and build assets
        run: |
          npm ci
          npm run build

      - name: 🔑 Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: 🚀 Sync built assets to server (No Node on Server!)
        run: |
          rsync -avz --delete public/build/ ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:/var/www/devsense/prod/public/build/

      - name: 🔄 Run Deploy Script
        run: |
          ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "cd /var/www/devsense/prod && bash deploy.sh"

